services:
    service1:
        command: /my/scripts/run
        #command: sleep infinity
        depends_on:
            - fluentdService
        environment:
            - FLUENTD_SERVICE_ADDRESS=$TEST_LOGGING_FLUENTDSERVICE_IPV4_ADDRESS
            - FLUENTD_SERVICE_PORT=$TEST_LOGGING_FLUENTDSERVICE_IPV4_PORT
        image: service
        networks:
            testLoggingNetwork:
                ipv4_address: $TEST_LOGGING_SERVICE1_IPV4_ADDRESS
        volumes:
            - type: bind
              source: ../../build-test_logging-Desktop-Debug
              target: /my/app
            - type: bind
              source: ./scripts/service
              target: /my/scripts
            - type: bind
              source: /usr/lib/x86_64-linux-gnu/
              target: /usr/lib/x86_64-linux-gnu/mySharedLibs

    service2:
        command: /my/scripts/run
        depends_on:
            - fluentdService
        environment:
            - FLUENTD_SERVICE_ADDRESS=$TEST_LOGGING_FLUENTDSERVICE_IPV4_ADDRESS
            - FLUENTD_SERVICE_PORT=$TEST_LOGGING_FLUENTDSERVICE_IPV4_PORT
        image: service
        networks:
            testLoggingNetwork:
                ipv4_address: $TEST_LOGGING_SERVICE2_IPV4_ADDRESS
        volumes:
            - type: bind
              source: ../../build-test_logging-Desktop-Debug
              target: /my/app
            - type: bind
              source: ./scripts/service
              target: /my/scripts
            - type: bind
              source: /usr/lib/x86_64-linux-gnu/
              target: /usr/lib/x86_64-linux-gnu/mySharedLibs

    fluentdService:
        command: fluentd -c /my/fluentd/conf
        #command: sleep infinity
        depends_on:
            - dbService
        environment:
            - DB_SERVICE_ADDRESS=$TEST_LOGGING_DBSERVICE_IPV4_ADDRESS
            - DB_SERVICE_PORT=$TEST_LOGGING_DBSERVICE_IPV4_PORT
            - DB_SERVICE_DATABASE=postgres
            - DB_SERVICE_USERNAME=$TEST_LOGGING_DBSERVICE_POSTGRES_USER
            - DB_SERVICE_PASSWORD=$TEST_LOGGING_DBSERVICE_POSTGRES_PASSWORD
        image: fluentdservice
        networks:
            testLoggingNetwork:
                ipv4_address: $TEST_LOGGING_FLUENTDSERVICE_IPV4_ADDRESS
        ports:
            - $TEST_LOGGING_FLUENTDSERVICE_IPV4_PORT:$TEST_LOGGING_FLUENTDSERVICE_IPV4_PORT
        volumes:
            - type: bind
              source: ./conf/fluentd
              target: /my/fluentd

    dbService:
        image: dbservice
        networks:
            testLoggingNetwork:
                ipv4_address: $TEST_LOGGING_DBSERVICE_IPV4_ADDRESS
        ports:
            - $TEST_LOGGING_DBSERVICE_IPV4_PORT:$TEST_LOGGING_DBSERVICE_IPV4_PORT
        environment:
            - POSTGRES_USER=$TEST_LOGGING_DBSERVICE_POSTGRES_USER
            - POSTGRES_PASSWORD=$TEST_LOGGING_DBSERVICE_POSTGRES_PASSWORD
        volumes:
            - testLoggingDbVolume:/var/lib/postgresql/data
            - type: bind
              source: ./scripts/sql
              target: /docker-entrypoint-initdb.d

volumes:
    testLoggingDbVolume:

networks:
    testLoggingNetwork:
        external: true
        driver: bridge
        ipam:
            config:
                - subnet: $TEST_LOGGING_DOCKER_NETWORK
